---
apiVersion: v1
kind: Service
metadata:
  name: mcp-proxy-hass
  namespace: llm
spec:
  selector:
    app: mcp-proxy-hass
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: sse
  type: ClusterIP
