apiVersion: v1
kind: Service
metadata:
  name: llamastack-proxy
  namespace: llm
  labels:
    app: llamastack-proxy
spec:
  type: ClusterIP
  selector:
    app: llamastack-proxy
  ports:
  - name: http
    port: 8322
    targetPort: 8322
    protocol: TCP
